skip_tags: true

environment:
  RUBY_VERSION: 24-x64

init:
  - git config --global core.autocrlf true

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - ridk enable
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
